window.instructorsMap = {  
  "Bader Khan": {
    photo: "Bader.jpg",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "GN101 - Safety Management System (SMS)",
      "RM001 -Ramp Airside Safety",
      "RM100 - Airside Driving",
      "RM202 - Turnaround Coordination",
      "WS001 - Wheelchair Service Handling",
    ]
  },
  "Dawood Alameri": {
    photo: "placeholder",
    authorized_for: [
      "RM003 - Basic Ramp Hand Signals",
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM105 - Ground Power Unit (GPU)",
      "RM106 - Air Conditioning Unit (ACU)",
      "RM107 - Air Starter Unit (ASU)",
      "RM115 - Aircraft Pushback - Conventional",
      "RM201 - Aircraft Marshaling",
      "RM205 - Headset Communication",
      "RM210 - Aircraft Pushback - Towbarless",
    ]
  },
  "Faisal Almohani": {
    photo: "placeholder",
    authorized_for: [
      "RM101 - Basic GSE Operation Airside",
      "RM103 - Conveyer Belt Loader",
      "RM110 - Passenger Stairs",
    ]
  },
  "Faris Alsaidalani": {
    photo: "placeholder",
    authorized_for: [
      "AB002 - Aircraft Loading/Unloading Awareness",
      "RM004 - Aircraft Loading/Unloading",
      "RM202 - Turnaround Coordination",
    ]
  },
  "Hammad Alhamoud": {
    photo: "placeholder",
    authorized_for: [
      "RM003 - Basic Ramp Hand Signals",
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM108 - Lavatory Truck",
      "RM109 - Water Truck",
      "RM119 - Aircraft Cleaning (Cabin)",
      "RM121 - Water and Lavatory Service Principles",
    ]
  },
  "Hassan Alsharif": {
    photo: "placeholder",
    authorized_for: [
      "PX000 - Passenger Handling Course",
      "PX001 - Passenger Handling-Meet and Greet",
      "PX002 - Passenger Handling-Check-In",
      "PX003 - Passenger Handling-Arrivals/Departure",
      "PX004 - Passenger Handling-Baggage Services, Claims and Settlement",
      "PX006 - Passenger Handling-Special Category Passengers and Passengers with Disabilities",
      "PX101 - Passenger Handling-Transit ,Transfer, and Connection",
    ]
  },
  "Hatoon Mahboob": {
    photo: "placeholder",
    authorized_for: [
      "RM119 - Aircraft Cleaning (Cabin)",
    ]
  },
  "Hattan Abdullah": {
    photo: "placeholder",
    authorized_for: [
      "RM003 - Basic Ramp Hand Signals",
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM105 - Ground Power Unit (GPU)",
      "RM106 - Air Conditioning Unit (ACU)",
      "RM107 - Air Starter Unit (ASU)",
      "RM115 - Aircraft Pushback - Conventional",
      "RM210 - Aircraft Pushback - Towbarless",
    ]
  },
  "Hattan Toukhi": {
    photo: "Hattan.jpg",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "AD002 - Dangerous Goods Regulations for personnel responsible for supporting loading and unloading ULDs, and aircraft cargo compartments activities",
      "DG201 - Dangerous Goods Regulations for Personnel Responsible for transporting cargo, loading and unloading ULDs, and aircraft cargo compartments",
      "DG202 - Dangerous Goods Regulations for Personnel Responsible for Accepting Passenger and Crew Baggage, Managing Aircraft Boarding Areas, and other Functions Involving Direct Passenger Contact at an Airport",
      "DG203 - Dangerous Goods Regulations for Personnel Responsible for Planning of Aircraft Loading",
      "DG204 - Dangerous Goods Regulations Personnel Responsible for supervising loading and unloading ULDs and aircraft cargo compartments",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "GN101 - Safety Management System (SMS)",
      "ID001 - Induction Program",
      "PX000 - Passenger Handling Course",
      "PX001 - Passenger Handling-Meet and Greet",
      "PX002 - Passenger Handling-Check-In",
      "PX003 - Passenger Handling-Arrivals/Departure",
      "PX004 - Passenger Handling-Baggage Services, Claims and Settlement",
      "PX006 - Passenger Handling-Special Category Passengers and Passengers with Disabilities",
      "PX101 - Passenger Handling-Transit ,Transfer, and Connection",
      "RM001 -Ramp Airside Safety",
      "RM100 - Airside Driving",
    ]
  },
  "Hazim A. Alhazmi": {
    photo: "Hazim.png",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "RM001 -Ramp Airside Safety",
      "RM003 - Basic Ramp Hand Signals",
      "RM100 - Airside Driving",
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM105 - Ground Power Unit (GPU)",
      "RM106 - Air Conditioning Unit (ACU)",
      "RM107 - Air Starter Unit (ASU)",
      "RM201 - Aircraft Marshaling",
      "RM209 - Helicopter Marshaling",
    ]
  },
  "Jamal Khan": {
    photo: "Jamal.jpg",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "AB002 - Aircraft Loading/Unloading Awareness",
      "AB003 - Baggage Handling Awareness",
      "AD002 - Dangerous Goods Regulations for personnel responsible for supporting loading and unloading ULDs, and aircraft cargo compartments activities",
      "DG201 - Dangerous Goods Regulations for Personnel Responsible for transporting cargo, loading and unloading ULDs, and aircraft cargo compartments",
      "DG202 - Dangerous Goods Regulations for Personnel Responsible for Accepting Passenger and Crew Baggage, Managing Aircraft Boarding Areas, and other Functions Involving Direct Passenger Contact at an Airport",
      "DG203 - Dangerous Goods Regulations for Personnel Responsible for Planning of Aircraft Loading",
      "DG204 - Dangerous Goods Regulations Personnel Responsible for supervising loading and unloading ULDs and aircraft cargo compartments",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "GN101 - Safety Management System (SMS)",
      "RM001 -Ramp Airside Safety",
      "RM003 - Basic Ramp Hand Signals",
      "RM004 - Aircraft Loading/Unloading",
      "RM100 - Airside Driving",
      "RM117 - Baggage Handling [Make-Up]",
      "RM202 - Turnaround Coordination",
    ]
  },
  "Joseph Mencias": {
    photo: "placeholder",
    authorized_for: [
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM108 - Lavatory Truck",
      "RM109 - Water Truck",
      "RM121 - Water and Lavatory Service Principles",
    ]
  },
  "Khaled Yaldash": {
    photo: "placeholder",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "AB002 - Aircraft Loading/Unloading Awareness",
      "AB003 - Baggage Handling Awareness",
      "AD002 - Dangerous Goods Regulations for personnel responsible for supporting loading and unloading ULDs, and aircraft cargo compartments activities",
      "DG201 - Dangerous Goods Regulations for Personnel Responsible for transporting cargo, loading and unloading ULDs, and aircraft cargo compartments",
      "DG202 - Dangerous Goods Regulations for Personnel Responsible for Accepting Passenger and Crew Baggage, Managing Aircraft Boarding Areas, and other Functions Involving Direct Passenger Contact at an Airport",
      "DG203 - Dangerous Goods Regulations for Personnel Responsible for Planning of Aircraft Loading",
      "DG204 - Dangerous Goods Regulations Personnel Responsible for supervising loading and unloading ULDs and aircraft cargo compartments",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "GN008 - Supervision and Oversight",
      "GN101 - Safety Management System (SMS)",
      "ID001 - Induction Program",
      "RM001 -Ramp Airside Safety",
      "RM003 - Basic Ramp Hand Signals",
      "RM004 - Aircraft Loading/Unloading",
      "RM101 - Basic GSE Operation Airside",
      "RM108 - Lavatory Truck",
      "RM109 - Water Truck",
      "RM117 - Baggage Handling [Make-Up]",
      "RM119 - Aircraft Cleaning (Cabin)",
      "RM121 - Water and Lavatory Service Principles",
      "RM202 - Turnaround Coordination",
    ]
  },
  "Khalid Alhunaki": {
    photo: "placeholder",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "ID001 - Induction Program",
      "RM001 -Ramp Airside Safety",
      "RM202 - Turnaround Coordination",
    ]
  },
  "Kholoud Babteen": {
    photo: "placeholder",
    authorized_for: [
      "PX000 - Passenger Handling Course",
      "PX001 - Passenger Handling-Meet and Greet",
      "PX002 - Passenger Handling-Check-In",
      "PX003 - Passenger Handling-Arrivals/Departure",
      "PX004 - Passenger Handling-Baggage Services, Claims and Settlement",
      "PX005 - Service Image",
      "PX006 - Passenger Handling-Special Category Passengers and Passengers with Disabilities",
      "PX101 - Passenger Handling-Transit ,Transfer, and Connection",
    ]
  },
  "Majed Almutari": {
    photo: "placeholder",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "AD002 - Dangerous Goods Regulations for personnel responsible for supporting loading and unloading ULDs, and aircraft cargo compartments activities",
      "DG201 - Dangerous Goods Regulations for Personnel Responsible for transporting cargo, loading and unloading ULDs, and aircraft cargo compartments",
      "DG202 - Dangerous Goods Regulations for Personnel Responsible for Accepting Passenger and Crew Baggage, Managing Aircraft Boarding Areas, and other Functions Involving Direct Passenger Contact at an Airport",
      "DG203 - Dangerous Goods Regulations for Personnel Responsible for Planning of Aircraft Loading",
      "DG204 - Dangerous Goods Regulations Personnel Responsible for supervising loading and unloading ULDs and aircraft cargo compartments",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "GN101 - Safety Management System (SMS)",
      "PX000 - Passenger Handling Course",
      "PX001 - Passenger Handling-Meet and Greet",
      "PX002 - Passenger Handling-Check-In",
      "PX003 - Passenger Handling-Arrivals/Departure",
      "PX004 - Passenger Handling-Baggage Services, Claims and Settlement",
      "PX006 - Passenger Handling-Special Category Passengers and Passengers with Disabilities",
      "PX101 - Passenger Handling-Transit ,Transfer, and Connection",
      "RM001 -Ramp Airside Safety",
      "WS001 - Wheelchair Service Handling",
    ]
  },
  "Masad Al-Sulami": {
    photo: "placeholder",
    authorized_for: [
      "GN101 - Safety Management System (SMS)",
      "RM003 - Basic Ramp Hand Signals",
      "RM100 - Airside Driving",
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM103 - Conveyer Belt Loader",
      "RM104 - Forklift",
      "RM105 - Ground Power Unit (GPU)",
      "RM106 - Air Conditioning Unit (ACU)",
      "RM107 - Air Starter Unit (ASU)",
      "RM108 - Lavatory Truck",
      "RM109 - Water Truck",
      "RM110 - Passenger Stairs",
      "RM112 - Medical Lift",
      "RM113 - ULD Transporter",
      "RM114 - ULD Loader",
      "RM115 - Aircraft Pushback - Conventional",
      "RM118 - Manlift",
      "RM121 - Water and Lavatory Service Principles",
      "RM201 - Aircraft Marshaling",
      "RM205 - Headset Communication",
      "RM208 - Gulfstream Pushback (G4-G3)",
      "RM209 - Helicopter Marshaling",
      "RM210 - Aircraft Pushback - Towbarless",
    ]
  },
  "Meshari Alonazi": {
    photo: "placeholder",
    authorized_for: [
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM103 - Conveyer Belt Loader",
      "RM110 - Passenger Stairs",
      "RM112 - Medical Lift",
      "RM113 - ULD Transporter",
      "RM114 - ULD Loader",
    ]
  },
  "Mohammad  Alharbi": {
    photo: "placeholder",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "ID001 - Induction Program",
      "RM001 -Ramp Airside Safety",
    ]
  },
  "Mohammed Albogdadi": {
    photo: "placeholder",
    authorized_for: [
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM108 - Lavatory Truck",
      "RM109 - Water Truck",
      "RM121 - Water and Lavatory Service Principles",
    ]
  },
  "Mohammed Alsamiti": {
    photo: "placeholder",
    authorized_for: [
      "RM003 - Basic Ramp Hand Signals",
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM105 - Ground Power Unit (GPU)",
      "RM106 - Air Conditioning Unit (ACU)",
      "RM107 - Air Starter Unit (ASU)",
      "RM115 - Aircraft Pushback - Conventional",
      "RM201 - Aircraft Marshaling",
      "RM210 - Aircraft Pushback - Towbarless",
    ]
  },
  "Mohammed Alyakoub": {
    photo: "placeholder",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "AD002 - Dangerous Goods Regulations for personnel responsible for supporting loading and unloading ULDs, and aircraft cargo compartments activities",
      "DG201 - Dangerous Goods Regulations for Personnel Responsible for transporting cargo, loading and unloading ULDs, and aircraft cargo compartments",
      "DG202 - Dangerous Goods Regulations for Personnel Responsible for Accepting Passenger and Crew Baggage, Managing Aircraft Boarding Areas, and other Functions Involving Direct Passenger Contact at an Airport",
      "DG203 - Dangerous Goods Regulations for Personnel Responsible for Planning of Aircraft Loading",
      "DG204 - Dangerous Goods Regulations Personnel Responsible for supervising loading and unloading ULDs and aircraft cargo compartments",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "GN008 - Supervision and Oversight",
      "GN101 - Safety Management System (SMS)",
      "ID001 - Induction Program",
      "PX000 - Passenger Handling Course",
      "PX001 - Passenger Handling-Meet and Greet",
      "PX002 - Passenger Handling-Check-In",
      "PX003 - Passenger Handling-Arrivals/Departure",
      "PX004 - Passenger Handling-Baggage Services, Claims and Settlement",
      "PX006 - Passenger Handling-Special Category Passengers and Passengers with Disabilities",
      "PX101 - Passenger Handling-Transit ,Transfer, and Connection",
      "RM001 -Ramp Airside Safety",
      "RM202 - Turnaround Coordination",
    ]
  },
  "Mohammed Turi": {
    photo: "placeholder",
    authorized_for: [
      "PX000 - Passenger Handling Course",
      "PX001 - Passenger Handling-Meet and Greet",
      "PX002 - Passenger Handling-Check-In",
      "PX003 - Passenger Handling-Arrivals/Departure",
      "PX004 - Passenger Handling-Baggage Services, Claims and Settlement",
      "PX006 - Passenger Handling-Special Category Passengers and Passengers with Disabilities",
      "PX101 - Passenger Handling-Transit ,Transfer, and Connection",
    ]
  },
  "Mohanad Seibah": {
    photo: "placeholder",
    authorized_for: [
      "GN003 - Emergency Response Awareness",
    ]
  },
  "Mohsen Abuzinadah": {
    photo: "placeholder",
    authorized_for: [
      "RM003 - Basic Ramp Hand Signals",
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
    ]
  },
  "Mustafa Kolagote": {
    photo: "Mustafa.jpg",
    authorized_for: [
      "RM003 - Basic Ramp Hand Signals",
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM103 - Conveyer Belt Loader",
      "RM104 - Forklift",
      "RM105 - Ground Power Unit (GPU)",
      "RM106 - Air Conditioning Unit (ACU)",
      "RM107 - Air Starter Unit (ASU)",
      "RM110 - Passenger Stairs",
      "RM112 - Medical Lift",
      "RM113 - ULD Transporter",
      "RM114 - ULD Loader",
      "RM115 - Aircraft Pushback - Conventional",
    ]
  },
  "Noura Aldubayan": {
    photo: "placeholder",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "AD002 - Dangerous Goods Regulations for personnel responsible for supporting loading and unloading ULDs, and aircraft cargo compartments activities",
      "DG201 - Dangerous Goods Regulations for Personnel Responsible for transporting cargo, loading and unloading ULDs, and aircraft cargo compartments",
      "DG202 - Dangerous Goods Regulations for Personnel Responsible for Accepting Passenger and Crew Baggage, Managing Aircraft Boarding Areas, and other Functions Involving Direct Passenger Contact at an Airport",
      "DG203 - Dangerous Goods Regulations for Personnel Responsible for Planning of Aircraft Loading",
      "DG204 - Dangerous Goods Regulations Personnel Responsible for supervising loading and unloading ULDs and aircraft cargo compartments",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "GN101 - Safety Management System (SMS)",
      "ID001 - Induction Program",
      "PX000 - Passenger Handling Course",
      "PX001 - Passenger Handling-Meet and Greet",
      "PX002 - Passenger Handling-Check-In",
      "PX003 - Passenger Handling-Arrivals/Departure",
      "PX004 - Passenger Handling-Baggage Services, Claims and Settlement",
      "PX006 - Passenger Handling-Special Category Passengers and Passengers with Disabilities",
      "PX101 - Passenger Handling-Transit ,Transfer, and Connection",
    ]
  },
  "Omar Albarakati": {
    photo: "placeholder",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "RM001 -Ramp Airside Safety",
    ]
  },
  "Prakash Balram": {
    photo: "placeholder",
    authorized_for: [
      "RM101 - Basic GSE Operation Airside",
      "RM103 - Conveyer Belt Loader",
      "RM110 - Passenger Stairs",
      "RM112 - Medical Lift",
      "RM113 - ULD Transporter",
      "RM114 - ULD Loader",
    ]
  },
  "Radwan Thani": {
    photo: "placeholder",
    authorized_for: [
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM103 - Conveyer Belt Loader",
      "RM110 - Passenger Stairs",
      "RM113 - ULD Transporter",
      "RM114 - ULD Loader",
    ]
  },

  "Rafa Sadawi": {
    photo: "placeholder",
    authorized_for: [
      "PX000 - Passenger Handling Course",
      "PX001 - Passenger Handling-Meet and Greet",
      "PX002 - Passenger Handling-Check-In",
      "PX003 - Passenger Handling-Arrivals/Departure",
      "PX004 - Passenger Handling-Baggage Services, Claims and Settlement",
      "PX006 - Passenger Handling-Special Category Passengers and Passengers with Disabilities",
      "PX101 - Passenger Handling-Transit ,Transfer, and Connection",
    ]
  },
  "Rayan Almolhim": {
    photo: "placeholder",
    authorized_for: [
      "AB002 - Aircraft Loading/Unloading Awareness",
      "RM004 - Aircraft Loading/Unloading",
      "RM116 - Aircraft Weight & Balance Familiarization",
      "RM203 -Aircraft W&B, Load Planning and Load Sheet",
      "RM204 - Documentation and messaging",
    ]
  },
  "Rayan Fakhrani": {
    photo: "placeholder",
    authorized_for: [
      "PX000 - Passenger Handling Course",
      "PX001 - Passenger Handling-Meet and Greet",
      "PX002 - Passenger Handling-Check-In",
      "PX003 - Passenger Handling-Arrivals/Departure",
      "PX004 - Passenger Handling-Baggage Services, Claims and Settlement",
      "PX006 - Passenger Handling-Special Category Passengers and Passengers with Disabilities",
      "PX101 - Passenger Handling-Transit ,Transfer, and Connection",
    ]
  },
  "Saeed Alsager": {
    photo: "placeholder",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "AB002 - Aircraft Loading/Unloading Awareness",
      "AB003 - Baggage Handling Awareness",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "GN101 - Safety Management System (SMS)",
      "RM001 -Ramp Airside Safety",
      "RM004 - Aircraft Loading/Unloading",
      "RM117 - Baggage Handling [Make-Up]",
    ]
  },
  "Safwan A. Alakhdari": {
    photo: "placeholder",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "AD002 - Dangerous Goods Regulations for personnel responsible for supporting loading and unloading ULDs, and aircraft cargo compartments activities",
      "DG201 - Dangerous Goods Regulations for Personnel Responsible for transporting cargo, loading and unloading ULDs, and aircraft cargo compartments",
      "DG202 - Dangerous Goods Regulations for Personnel Responsible for Accepting Passenger and Crew Baggage, Managing Aircraft Boarding Areas, and other Functions Involving Direct Passenger Contact at an Airport",
      "DG203 - Dangerous Goods Regulations for Personnel Responsible for Planning of Aircraft Loading",
      "DG204 - Dangerous Goods Regulations Personnel Responsible for supervising loading and unloading ULDs and aircraft cargo compartments",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "GN101 - Safety Management System (SMS)",
      "ID001 - Induction Program",
      "RM001 -Ramp Airside Safety",
      "RM116 - Aircraft Weight & Balance Familiarization",
      "RM202 - Turnaround Coordination",
      "RM203 -Aircraft W&B, Load Planning and Load Sheet",
      "RM204 - Documentation and messaging",
    ]
  },
  "Saleh Mahallawi": {
    photo: "placeholder",
    authorized_for: [
      "RM003 - Basic Ramp Hand Signals",
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM103 - Conveyer Belt Loader",
      "RM104 - Forklift",
      "RM105 - Ground Power Unit (GPU)",
      "RM106 - Air Conditioning Unit (ACU)",
      "RM107 - Air Starter Unit (ASU)",
      "RM108 - Lavatory Truck",
      "RM109 - Water Truck",
      "RM110 - Passenger Stairs",
      "RM112 - Medical Lift",
      "RM113 - ULD Transporter",
      "RM114 - ULD Loader",
      "RM115 - Aircraft Pushback - Conventional",
      "RM118 - Manlift",
      "RM121 - Water and Lavatory Service Principles",
      "RM201 - Aircraft Marshaling",
      "RM205 - Headset Communication",
      "RM208 - Gulfstream Pushback (G4-G3)",
      "RM209 - Helicopter Marshaling",
      "RM210 - Aircraft Pushback - Towbarless",
    ]
  },
  "Saleh Manfaloti": {
    photo: "placeholder",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "PX000 - Passenger Handling Course",
      "PX001 - Passenger Handling-Meet and Greet",
      "PX002 - Passenger Handling-Check-In",
      "PX003 - Passenger Handling-Arrivals/Departure",
      "PX004 - Passenger Handling-Baggage Services, Claims and Settlement",
      "PX006 - Passenger Handling-Special Category Passengers and Passengers with Disabilities",
      "PX101 - Passenger Handling-Transit ,Transfer, and Connection",
      "RM001 -Ramp Airside Safety",
    ]
  },
  "Samih Elmanasir": {
    photo: "Samih.jpeg",
    authorized_for: [
      "RM003 - Basic Ramp Hand Signals",
      "RM100 - Airside Driving",
      "RM101 - Basic GSE Operation Airside",
      "RM115 - Aircraft Pushback - Conventional",
      "RM210 - Aircraft Pushback - Towbarless",
    ]
  },
  "Sharaf M. Alzahrani": {
    photo: "Sharaf.JPG",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "GN101 - Safety Management System (SMS)",
      "PX000 - Passenger Handling Course",
      "PX001 - Passenger Handling-Meet and Greet",
      "PX002 - Passenger Handling-Check-In",
      "PX003 - Passenger Handling-Arrivals/Departure",
      "PX004 - Passenger Handling-Baggage Services, Claims and Settlement",
      "PX005 - Service Image",
      "PX006 - Passenger Handling-Special Category Passengers and Passengers with Disabilities",
      "PX101 - Passenger Handling-Transit ,Transfer, and Connection",
      "RM001 -Ramp Airside Safety",
      "WS001 - Wheelchair Service Handling",
    ]
  },
  "Sultan Bassrawi": {
    photo: "Sultan B.png",
    authorized_for: [
      "GN008 - Supervision and Oversight",
      "GN010 - Train the Trainer",
    ]
  },
  "Talal  Almutairi": {
    photo: "placeholder",
    authorized_for: [
      "RM003 - Basic Ramp Hand Signals",
      "RM101 - Basic GSE Operation Airside",
      "RM105 - Ground Power Unit (GPU)",
      "RM106 - Air Conditioning Unit (ACU)",
      "RM107 - Air Starter Unit (ASU)",
      "RM115 - Aircraft Pushback - Conventional",
      "RM201 - Aircraft Marshaling",
      "RM210 - Aircraft Pushback - Towbarless",
    ]
  },
  "Talal Khalaf": {
    photo: "talal.png",
    authorized_for: [
      "RM003 - Basic Ramp Hand Signals",
      "RM100 - Airside Driving",
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM103 - Conveyer Belt Loader",
      "RM105 - Ground Power Unit (GPU)",
      "RM106 - Air Conditioning Unit (ACU)",
      "RM107 - Air Starter Unit (ASU)",
      "RM110 - Passenger Stairs",
      "RM115 - Aircraft Pushback - Conventional",
      "RM201 - Aircraft Marshaling",
      "RM209 - Helicopter Marshaling",
      "RM210 - Aircraft Pushback - Towbarless",
    ]
  },
  "Tariq Aloitaibi": {
    photo: "placeholder",
    authorized_for: [
      "RM003 - Basic Ramp Hand Signals",
      "RM100 - Airside Driving",
      "RM101 - Basic GSE Operation Airside",
      "RM108 - Lavatory Truck",
      "RM109 - Water Truck",
      "RM121 - Water and Lavatory Service Principles",
    ]
  },
  "Thamer Al-Amri": {
    photo: "placeholder",
    authorized_for: [
      "RM119 - Aircraft Cleaning (Cabin)",
    ]
  },
  "Turki Fallatah": {
    photo: "Turki.jpg",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "AD002 - Dangerous Goods Regulations for personnel responsible for supporting loading and unloading ULDs, and aircraft cargo compartments activities",
      "DG201 - Dangerous Goods Regulations for Personnel Responsible for transporting cargo, loading and unloading ULDs, and aircraft cargo compartments",
      "DG202 - Dangerous Goods Regulations for Personnel Responsible for Accepting Passenger and Crew Baggage, Managing Aircraft Boarding Areas, and other Functions Involving Direct Passenger Contact at an Airport",
      "DG203 - Dangerous Goods Regulations for Personnel Responsible for Planning of Aircraft Loading",
      "DG204 - Dangerous Goods Regulations Personnel Responsible for supervising loading and unloading ULDs and aircraft cargo compartments",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "GN101 - Safety Management System (SMS)",
      "RM001 -Ramp Airside Safety",
      "RM003 - Basic Ramp Hand Signals",
      "RM100 - Airside Driving",
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM105 - Ground Power Unit (GPU)",
      "RM106 - Air Conditioning Unit (ACU)",
      "RM107 - Air Starter Unit (ASU)",
      "RM201 - Aircraft Marshaling",
    ]
  },
  "Wasel Alwasel": {
    photo: "placeholder",
    authorized_for: [
      "PX000 - Passenger Handling Course",
      "PX001 - Passenger Handling-Meet and Greet",
      "PX002 - Passenger Handling-Check-In",
      "PX003 - Passenger Handling-Arrivals/Departure",
      "PX004 - Passenger Handling-Baggage Services, Claims and Settlement",
      "PX006 - Passenger Handling-Special Category Passengers and Passengers with Disabilities",
      "PX101 - Passenger Handling-Transit ,Transfer, and Connection",
    ]
  },
  "Wesam K. Zainiy": {
    photo: "Wesam Zainy.jpg",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "AB002 - Aircraft Loading/Unloading Awareness",
      "AD002 - Dangerous Goods Regulations for personnel responsible for supporting loading and unloading ULDs, and aircraft cargo compartments activities",
      "DG201 - Dangerous Goods Regulations for Personnel Responsible for transporting cargo, loading and unloading ULDs, and aircraft cargo compartments",
      "DG202 - Dangerous Goods Regulations for Personnel Responsible for Accepting Passenger and Crew Baggage, Managing Aircraft Boarding Areas, and other Functions Involving Direct Passenger Contact at an Airport",
      "DG203 - Dangerous Goods Regulations for Personnel Responsible for Planning of Aircraft Loading",
      "DG204 - Dangerous Goods Regulations Personnel Responsible for supervising loading and unloading ULDs and aircraft cargo compartments",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "GN101 - Safety Management System (SMS)",
      "ID001 - Induction Program",
      "RM001 -Ramp Airside Safety",
      "RM004 - Aircraft Loading/Unloading",
      "RM116 - Aircraft Weight & Balance Familiarization",
      "RM202 - Turnaround Coordination",
      "RM203 -Aircraft W&B, Load Planning and Load Sheet",
      "RM204 - Documentation and messaging",
    ]
  },
  "Abdulaziz Trengganu": {
    photo: "placeholder",
    authorized_for: [
      "AB002 - Aircraft Loading/Unloading Awareness",
      "AB003 - Baggage Handling Awareness",
      "AD002 - Dangerous Goods Regulations for personnel responsible for supporting loading and unloading ULDs, and aircraft cargo compartments activities",
      "DG201 - Dangerous Goods Regulations for Personnel Responsible for transporting cargo, loading and unloading ULDs, and aircraft cargo compartments",
      "DG202 - Dangerous Goods Regulations for Personnel Responsible for Accepting Passenger and Crew Baggage, Managing Aircraft Boarding Areas, and other Functions Involving Direct Passenger Contact at an Airport",
      "DG203 - Dangerous Goods Regulations for Personnel Responsible for Planning of Aircraft Loading",
      "DG204 - Dangerous Goods Regulations Personnel Responsible for supervising loading and unloading ULDs and aircraft cargo compartments",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN101 - Safety Management System (SMS)",
      "RM004 - Aircraft Loading/Unloading",
      "RM116 - Aircraft Weight & Balance Familiarization",
      "RM117 - Baggage Handling [Make-Up]",
      "RM202 - Turnaround Coordination",
    ]
  },
  "Abdulelah Nasir": {
    photo: "placeholder",
    authorized_for: [
      "PX000 - Passenger Handling Course",
      "PX001 - Passenger Handling-Meet and Greet",
      "PX002 - Passenger Handling-Check-In",
      "PX003 - Passenger Handling-Arrivals/Departure",
      "PX004 - Passenger Handling-Baggage Services, Claims and Settlement",
      "PX006 - Passenger Handling-Special Category Passengers and Passengers with Disabilities",
      "PX101 - Passenger Handling-Transit ,Transfer, and Connection",
    ]
  },
  "Abdullah  Alqahtani": {
    photo: "placeholder",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "RM001 -Ramp Airside Safety",
    ]
  },
  "Abdullah Abo Asker": {
    photo: "placeholder",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "AB002 - Aircraft Loading/Unloading Awareness",
      "AB003 - Baggage Handling Awareness",
      "AD002 - Dangerous Goods Regulations for personnel responsible for supporting loading and unloading ULDs, and aircraft cargo compartments activities",
      "DG201 - Dangerous Goods Regulations for Personnel Responsible for transporting cargo, loading and unloading ULDs, and aircraft cargo compartments",
      "DG202 - Dangerous Goods Regulations for Personnel Responsible for Accepting Passenger and Crew Baggage, Managing Aircraft Boarding Areas, and other Functions Involving Direct Passenger Contact at an Airport",
      "DG203 - Dangerous Goods Regulations for Personnel Responsible for Planning of Aircraft Loading",
      "DG204 - Dangerous Goods Regulations Personnel Responsible for supervising loading and unloading ULDs and aircraft cargo compartments",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "GN008 - Supervision and Oversight",
      "GN101 - Safety Management System (SMS)",
      "ID001 - Induction Program",
      "RM001 -Ramp Airside Safety",
      "RM004 - Aircraft Loading/Unloading",
      "RM116 - Aircraft Weight & Balance Familiarization",
      "RM117 - Baggage Handling [Make-Up]",
      "RM202 - Turnaround Coordination",
      "RM203 -Aircraft W&B, Load Planning and Load Sheet",
      "RM204 - Documentation and messaging",
    ]
  },
  "Abdullah Alharbi": {
    photo: "placeholder",
    authorized_for: [
      "PX000 - Passenger Handling Course",
      "PX001 - Passenger Handling-Meet and Greet",
      "PX002 - Passenger Handling-Check-In",
      "PX003 - Passenger Handling-Arrivals/Departure",
      "PX004 - Passenger Handling-Baggage Services, Claims and Settlement",
      "PX006 - Passenger Handling-Special Category Passengers and Passengers with Disabilities",
      "PX101 - Passenger Handling-Transit ,Transfer, and Connection",
    ]
  },
  "Abdullah Almuzahel": {
    photo: "placeholder",
    authorized_for: [
      "RM003 - Basic Ramp Hand Signals",
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
    ]
  },
  "Abdullah Alshabaan": {
    photo: "placeholder",
    authorized_for: [
      "RM100 - Airside Driving",
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM103 - Conveyer Belt Loader",
      "RM110 - Passenger Stairs",
      "RM113 - ULD Transporter",
      "RM114 - ULD Loader",
    ]
  },
  "Abdullah M.Altorair": {
    photo: "placeholder",
    authorized_for: [
      "AD002 - Dangerous Goods Regulations for personnel responsible for supporting loading and unloading ULDs, and aircraft cargo compartments activities",
      "DG201 - Dangerous Goods Regulations for Personnel Responsible for transporting cargo, loading and unloading ULDs, and aircraft cargo compartments",
      "DG202 - Dangerous Goods Regulations for Personnel Responsible for Accepting Passenger and Crew Baggage, Managing Aircraft Boarding Areas, and other Functions Involving Direct Passenger Contact at an Airport",
      "DG203 - Dangerous Goods Regulations for Personnel Responsible for Planning of Aircraft Loading",
      "DG204 - Dangerous Goods Regulations Personnel Responsible for supervising loading and unloading ULDs and aircraft cargo compartments",
      "RM202 - Turnaround Coordination",
    ]
  },
  "Adam Sider": {
    photo: "placeholder",
    authorized_for: [
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "GN101 - Safety Management System (SMS)",
      "RM001 -Ramp Airside Safety",
    ]
  },
  "Ahmed Aba Hussain": {
    photo: "placeholder",
    authorized_for: [
      "AB001 - General Aviation & Safety Fundamentals",
      "AB002 - Aircraft Loading/Unloading Awareness",
      "AB003 - Baggage Handling Awareness",
      "AD002 - Dangerous Goods Regulations for personnel responsible for supporting loading and unloading ULDs, and aircraft cargo compartments activities",
      "DG201 - Dangerous Goods Regulations for Personnel Responsible for transporting cargo, loading and unloading ULDs, and aircraft cargo compartments",
      "DG202 - Dangerous Goods Regulations for Personnel Responsible for Accepting Passenger and Crew Baggage, Managing Aircraft Boarding Areas, and other Functions Involving Direct Passenger Contact at an Airport",
      "DG203 - Dangerous Goods Regulations for Personnel Responsible for Planning of Aircraft Loading",
      "DG204 - Dangerous Goods Regulations Personnel Responsible for supervising loading and unloading ULDs and aircraft cargo compartments",
      "GN001 - Basic Aviation, Safety and SMS",
      "GN002 - Aviation Security Awareness",
      "GN003 - Emergency Response Awareness",
      "GN004 - Airport Familiarization",
      "GN006 - Human Factors",
      "GN007 - Regulatory Awareness (Introduction to GACARs)",
      "ID001 - Induction Program",
      "PX000 - Passenger Handling Course",
      "PX001 - Passenger Handling-Meet and Greet",
      "PX002 - Passenger Handling-Check-In",
      "PX003 - Passenger Handling-Arrivals/Departure",
      "PX004 - Passenger Handling-Baggage Services, Claims and Settlement",
      "PX006 - Passenger Handling-Special Category Passengers and Passengers with Disabilities",
      "PX101 - Passenger Handling-Transit ,Transfer, and Connection",
      "RM001 -Ramp Airside Safety",
      "RM004 - Aircraft Loading/Unloading",
      "RM116 - Aircraft Weight & Balance Familiarization",
      "RM117 - Baggage Handling [Make-Up]",
      "RM202 - Turnaround Coordination",
      "RM203 -Aircraft W&B, Load Planning and Load Sheet",
      "RM204 - Documentation and messaging",
      "WS001 - Wheelchair Service Handling",
    ]
  },

  "Ahmed Alkhanbshi": {
    photo: "Khambashi.jpg",
    authorized_for: [
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "GN004 - Airport Familiarization",
      "RM100 - Airside Driving",
      "GN002 - Aviation Security Awareness",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "GN001 - Basic Aviation, Safety and SMS",
      "RM101 - Basic GSE Operation Airside",
      "RM003 - Basic Ramp Hand Signals",
      "GN003 - Emergency Response Awareness",
      "AB001 - General Aviation & Safety Fundamentals", 
      "RM205 - Headset Communication",
      "GN006 - Human Factors",
      "RM001 -Ramp Airside Safety",
      "GN007 - Regulatory Awareness (Introduction to GACARs) ",
      "GN101 - Safety Management System (SMS)",
      "DG202 - Dangerous Goods Regulations for Personnel Responsible for Accepting Passenger and Crew Baggage, Managing Aircraft Boarding Areas, and other Functions Involving Direct Passenger Contact at an Airport",
      "DG203 - Dangerous Goods Regulations for Personnel Responsible for Planning of Aircraft Loading",
      "AD002 - Dangerous Goods Regulations for personnel responsible for supporting loading and unloading ULDs, and aircraft cargo compartments activities", 
      "DG201 - Dangerous Goods Regulations for Personnel Responsible for transporting cargo, loading and unloading ULDs, and aircraft cargo compartments",
      "DG204 - Dangerous Goods Regulations Personnel Responsible for supervising loading and unloading ULDs and aircraft cargo compartments",
    ]
  },
  "Alwan Alshamry": {
    photo: "placeholder",
    authorized_for: [
      "RM003 - Basic Ramp Hand Signals",
      "RM100 - Airside Driving",
      "RM101 - Basic GSE Operation Airside",
      "RM102 - Baggage Tractor & Non-Motorized GSE",
      "RM105 - Ground Power Unit (GPU)",
      "RM106 - Air Conditioning Unit (ACU)",
      "RM107 - Air Starter Unit (ASU)",
      "RM115 - Aircraft Pushback - Conventional",
      "RM201 - Aircraft Marshaling",
      "RM205 - Headset Communication",
      "RM210 - Aircraft Pushback - Towbarless",
    ]
  },
  "Ammar Alfahad": {
    photo: "placeholder",
    authorized_for: [
      "ID001 - Induction Program",
      "PX005 - Service Image",
    ]
  },
};
console.log("Instructors loaded:", window.instructorsMap);